# --------------------------------------
# Model
# --------------------------------------
model_name: shufflenetv1
num_class: 92

# --------------------------------------
# Data Set
# --------------------------------------
data_name: fru92
k_fold: 0
EPOCH: 300

# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: sgd
lr: 0.01
train_batchsize: 256
test_batchsize: 256