strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
dataset_name: fru92_images
image_size: 224
multi_scale: null
test_crop_ratio: 0.9
# --------------------------------------
# Optimizer parameters
# --------------------------------------
opt: adamw
weight_decay: 0.05
momentum: 0.9
epochs: 300
clip_grad: null
precision: 16
# --------------------------------------
# Learning rate schedule parameters
# --------------------------------------
sched: cosine
lr: 0.04   # for bs=4096
warmup_lr: 0.000001
min_lr: 0.00001
warmup_epochs: 20
# --------------------------------------
# Distillation parameters
# --------------------------------------
teacher_model: regnety_160
distillation_type: none   # do not use KD by default
#distillation_type: hard  # should be better than soft
#distillation_type: soft
distillation_alpha: 0.5
distillation_tau: 1.0
# --------------------------------------
# Model parameters
# --------------------------------------
model_name: mobilenetv2_140

# --------------------------------------
# Augmentation parameters
# --------------------------------------
color_jitter: 0
aa: null
train_interpolation: bicubic    # Training interpolation (random, bilinear, bicubic default: "bicubic")
smoothing: 0.1    # Label smoothing
# Random Erase params
reprob: 0
remode: pixel
recount: 1
ode: batch       # How to apply mixup/cutmix params. Per "batch", "pair", or "elem"
mixup: -1
cutmix: -1
cutmix_minmax: null   # cutmix min/max ratio, overrides alpha and enables cutmix if set (default: None)
mixup_prob: 1.0         # Probability of performing mixup or cutmix when either/both is enabled
mixup_switch_prob: 0.5  # Probability of switching to cutmix when both mixup and cutmix enabled
mixup_mode: batch       # How to apply mixup/cutmix params. Per "batch", "pair", or "elem"